[Service]
ExecStart=
ExecStart=/bin/sh -c '. /etc/os-release; export PLEX_MEDIA_SERVER_INFO_VENDOR=$$NAME; export PLEX_MEDIA_SERVER_INFO_MODEL=$$(uname -m); export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION=$$VERSION_ID; exec "/usr/lib/plexmediaserver/Plex Media Server"'
Type=simple
User=root
Group=root
Restart=on-failure
RestartSec=5
StartLimitInterval=60s
StartLimitBurst=3
SyslogIdentifier=Plex Media Server
StandardOutput=journal
StandardError=journal
