---
- name: Wait for system to become reachable
  ansible.builtin.wait_for_connection:
    timeout: 60

- name: Now gather facts
  ansible.builtin.setup:

- name: Ensure AdGuard directory exists
  ansible.builtin.file:
    path: /opt/AdGuardHome
    state: directory
    mode: '0700'

- name: Get the latest AdGuard installation from GitHub
  ansible.builtin.uri:
    url: https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest
    return_content: true
  register: adguard_json_response

- name: Install/Update AdGuard
  ansible.builtin.unarchive:
    remote_src: true
    src: >-
      {{ adguard_json_response.json.assets |
      selectattr('name', 'match', 'AdGuardHome_linux_amd64.tar.gz') |
      map(attribute='browser_download_url') |
      first }}
    dest: "/opt"

- name: Install service
  ansible.builtin.copy:
    src: AdGuardHome.service
    dest: /etc/systemd/system/AdGuardHome.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Copy config from template
  ansible.builtin.template:
    src: AdGuardHome.yaml.j2
    dest: "/opt/AdGuardHome/AdGuardHome.yaml"
    owner: root
    group: root
    mode: '0644'
  notify: Restart service

- name: Ensure service is enabled and running
  ansible.builtin.systemd:
    name: AdGuardHome
    state: started
    enabled: true
    daemon_reload: true
