---
- name: Wait for system to become reachable
  ansible.builtin.wait_for_connection:
    timeout: 60

- name: Now gather facts
  ansible.builtin.setup:

- name: Create group and user
  ansible.builtin.user:
    name: git
    uid: 1000
    shell: /bin/bash
    home: /var/lib/gitea
    create_home: true
    state: present

- name: Update apt cache if it's older than 1 hour
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # 3,600 seconds = 1 hour

- name: Install required packages
  ansible.builtin.package:
    name:
      - sqlite3
      - git
    state: present

- name: Ensure Gitea directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: git
    group: git
    mode: '0755'
  loop:
    - "/var/lib/gitea"
    - "/var/lib/gitea/custom"
    - "/var/lib/gitea/data"
    - "/var/lib/gitea/log"
    - "/etc/gitea"

- name: Check current Gitea version
  ansible.builtin.command: "/var/lib/gitea/gitea --version"
  register: gitea_current_version
  failed_when: false
  changed_when: false

- name: Get latest release info
  ansible.builtin.uri:
    url: https://api.github.com/repos/go-gitea/gitea/releases/latest
    return_content: true
  register: gitea_json
  when: gitea_current_version.rc != 0 or gitea_json_response is not defined

- name: Install/Update binary
  ansible.builtin.get_url:
    url: |
      {{
        gitea_json.json.assets
        | selectattr('name', 'search', 'linux-amd64$')
        | map(attribute='browser_download_url')
        | first
      }}
    dest: "/var/lib/gitea/gitea"
    owner: git
    group: git
    mode: "0755"
  when: >
    gitea_current_version.rc != 0 or
    gitea_json.json.tag_name not in gitea_current_version.stdout
  notify: Restart service

- name: Configuration files
  block:
    - name: Create config file
      ansible.builtin.template:
        src: app.ini.j2
        dest: /etc/gitea/app.ini
        owner: git
        group: git
        mode: '0644'
      notify: Restart service

    - name: Create service
      ansible.builtin.copy:
        src: gitea.service
        dest: /lib/systemd/system/gitea.service
        owner: root
        group: root
        mode: '0644'
      notify: Reload systemd

- name: Ensure service is enabled and running
  ansible.builtin.systemd:
    name: gitea
    state: started
    enabled: true
